server:
  port: 6681
  #servlet:
  #context-path: /test
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
    application:
      name: component-redis

  redis: 0
  # Redis服务器地址
  host: 127.0.0.1
  # Redis服务器连接端口
  port: 6379
  # Redis服务器连接密码（默认为空）
  password:
  # 连接池最大连接数（使用负值表示没有限制）
  jedis:
    pool:
      max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）#
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 10000
  application:
    name: bd-job-executor-springboot
redis:
  time:
    tolive: 100000
  subscribe:
    info: com.tomcatwang.redis.service.TestService|receiveMessage|topictest,
netty:
  websocket :
    server:
      port: 12345